#1.设置日志登记，springboot默认只输出大于等于info级别的
#logging:
#  level:
#    root: trace

#2.只修改启动项的日志级别
logging:
  level:
    com:
      tulingxueyuan: trace
  # 日志样式
  #  pattern:
  #    console后面为默认的样式
  #    console:
  #      修改默认样式
  #    dataformat: -yyyy-MM-dd

  #    日志输出 不指定路径则在项目的相对路径之下
  file:
#    name: SystemOut.log
    name: e:/logs/SystemOut.log
    max-size: 5KB
#    path与name不同之处在于不可以指定日志名称，默认输出spring.log
#    path: D:/
