server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源，替换C3P0
    url: jdbc:mysql://localhost:3306/maven?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      tulingxueyuan: debug
mybatis-plus:
#  mp默认的mapper.xml路径是 classpath*:/mapper/**/*.xml,如果不是按下面的方式进行修改
  mapper-locations: classpath:/mapperzz/*.xml
